# Generated by Django 5.0.6 on 2024-05-30 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_userbookprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookProgress',
        ),
    ]
