# Generated by Django 5.0.6 on 2024-05-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text')], default='pdf', max_length=10),
        ),
    ]
