# Generated by Django 5.0.6 on 2024-05-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_book_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('text', 'Text'), ('word', 'Word'), ('excel', 'Excel')], default='pdf', max_length=10),
        ),
    ]
